env:
  global:
  - secure: Vre+k4OWu4wGqlZtKee3K0rVlTnmL6VklFECOLyrUz+6otlD8FzPQSIGlsKv26pE9YnwFNsZSWSGzSwpjmr6/cOuFD6sV3yycEjkK/J+RjxrjXYEQ7HHFYngu2jpOU4kLS7/nWck8av9o0Txea9qgrm2dDAN4rQPQ29SvYuZ5Z0601mTUF8R3Os1+HE0T5/Xfxg6oWBi7OSmiO58Wr6xf0IDbtKpegCdorNMfUFfNkrHQiyfPCofZfONpDoQyWVoWKvktFhvhrNu94yveInrQpS9LVltvGjjWWuIFcino8nGCmq4mlzpxJdtZ1ueXJbtoTrJx4g+TGUVGFgT0uqkw4rxGwYt2IALwOuw3gV3Mx/6eo71izYuGhhfjniOtjQn+LuDtbNHWvwumeibKLtueWIRsW+s2nLoPbR2TBL24Pqjk2RJOhWxQsS6zV6ipOuXaI+zlnDUYj0ZUGH0emE6+ZpMoIrleqnk5cvj1X+h58RHPJS1NNpcXIj9/QSPR+sylR4zAIJVhAwYK5/TeTFQCFDZ4WkwVpxC6rDLlavvE0/Kam3UU9ZdEgE0lzVvgYKEjv/GBAo6hKraNzInBGYKfrEY7ElE0rqkCtsG0Pjpdb7KmVEdgd0x53NwP+6q7wa6+us4O+HgDH/wbyoYkQtd24crSFJxOMOuwAnzehKO6N8=
  - secure: SgUOKic4fNU3Y1tIINDWSJ2nN9KlUrGLy5FXFvI9ij1+S2+nBMGKV/ux1Kxtf9LSmQ/1esRO/D0kmTgad8pgHrThkna7QeywlOFMibiVI/mgqpoSKS6CPloViWWC6qCsAO5FRcPhqDrrhlr2h/L6n3jWlSDfAraWCDs91BSHQUpSUWtVHvppOu9vMLy58di2T0B6f1Nfasoyb9AvlK3DZbx5l2EpIzg21x2NYRZII87IN5moGxF4v9aHxi+nluSWg3FEHcDrKw2vnU8wd8d5iW900ZTWnpLIcKvwOcs8VOr2iHwTHVtXfkFBbskcnm8wbmFGn2+qOu022ZGkfOxJgf1lnV3d93ETD7GxbnBQTz8UPmZbSmoOsAfMSlW3zivQ3cj8utMGT5cf0GmSpMf1pRt49t6SFoAxSCkuJ++dDMu+bZrUHlB44b9RJHW5Uh/5A7qL9SOuGcRk4H2kMDKDlIuDiWhOUjhZ0t7b9NaDQWgnig6Lx4Qbdbj44JjEqIf8nukuTiw2OwfUwt6FW5AE9XZEoq1ExXFW1Oz6ANPem6TZJmfeXBg+rXJqCMuiOZ0Fg5fcEdUaDF9kj7un4uizWbuLJ3LgCYRUmGdrSMPUL+OLDK4PnYz+pbM5hjxnSrJoPTfHHmSH0vRUoJmGktBX8KUccSc1tIYt+ppIA92fmcM=

services:
- docker

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull julienbayle/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t julienbayle/jplatformbuild
- docker cp buildimage:/root/dist .

deploy:
  provider: releases
  api_key:
    secure: iuOWVD2Qy5qhjFruMXGSFg/KHQKEPudJzYZTBqwueyY1x8U64dlxAE/aTgypmdwJRQNWveWZTRAmhcjLPNPdrEIoX7+MCwOj0a6Ar9uOVDdCQaE9aa26pDYKFGsf0BT4NBLcMf90J1Iw0lHI/A5ubiBrVISQBpQA0dNjTwoQsISa9I3+xTrJKjfYULMvUWq+DlVQJrlNY0SizrmxILrAwXYT/U2YOWpVyXIOpCjNbRtmDyLyZFuLdgum5E8+5iOzu8mLyNk2ajb3T5reX5eWJ0bSdbR0cMEg7MrzIltTtilPSJeVdnB3gYzXx71LixPNOiHyIVjBV645FD3ceuJQY8mLqGsDb/euMpiyQeh+mSdqdmEe1Sza95d2xoPy+VdZfFTZUHdrJ3U9vxOsP8YQ93OXANgJu3BW/87pcLulJc01Eg0VfUyiQfkJJ/sM2h4ZKObBAY/49Upt40jRBqebvUsf97WmORUc4/TbzfXDDlJ/nxdKXCqSTl7ObkytRKO0ZRkbLh4y9melFpu8ZTwrajV9lsVC1oWj8bRoBJDHvoWhBeWDI72jCrcteVC8Divy4/iYcDRxNIxR3qFLxKMAUzYAirshrPDL+v1SIIrLz8kTy/ZZwCcmA9dSRoMaiMUxYzDl4TPn3F3OE4p7HbBi7OHUtRspJvBTcqQ1sNZTlCc=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
