env:
  global:
  - secure: Vre+k4OWu4wGqlZtKee3K0rVlTnmL6VklFECOLyrUz+6otlD8FzPQSIGlsKv26pE9YnwFNsZSWSGzSwpjmr6/cOuFD6sV3yycEjkK/J+RjxrjXYEQ7HHFYngu2jpOU4kLS7/nWck8av9o0Txea9qgrm2dDAN4rQPQ29SvYuZ5Z0601mTUF8R3Os1+HE0T5/Xfxg6oWBi7OSmiO58Wr6xf0IDbtKpegCdorNMfUFfNkrHQiyfPCofZfONpDoQyWVoWKvktFhvhrNu94yveInrQpS9LVltvGjjWWuIFcino8nGCmq4mlzpxJdtZ1ueXJbtoTrJx4g+TGUVGFgT0uqkw4rxGwYt2IALwOuw3gV3Mx/6eo71izYuGhhfjniOtjQn+LuDtbNHWvwumeibKLtueWIRsW+s2nLoPbR2TBL24Pqjk2RJOhWxQsS6zV6ipOuXaI+zlnDUYj0ZUGH0emE6+ZpMoIrleqnk5cvj1X+h58RHPJS1NNpcXIj9/QSPR+sylR4zAIJVhAwYK5/TeTFQCFDZ4WkwVpxC6rDLlavvE0/Kam3UU9ZdEgE0lzVvgYKEjv/GBAo6hKraNzInBGYKfrEY7ElE0rqkCtsG0Pjpdb7KmVEdgd0x53NwP+6q7wa6+us4O+HgDH/wbyoYkQtd24crSFJxOMOuwAnzehKO6N8=
  - secure: SgUOKic4fNU3Y1tIINDWSJ2nN9KlUrGLy5FXFvI9ij1+S2+nBMGKV/ux1Kxtf9LSmQ/1esRO/D0kmTgad8pgHrThkna7QeywlOFMibiVI/mgqpoSKS6CPloViWWC6qCsAO5FRcPhqDrrhlr2h/L6n3jWlSDfAraWCDs91BSHQUpSUWtVHvppOu9vMLy58di2T0B6f1Nfasoyb9AvlK3DZbx5l2EpIzg21x2NYRZII87IN5moGxF4v9aHxi+nluSWg3FEHcDrKw2vnU8wd8d5iW900ZTWnpLIcKvwOcs8VOr2iHwTHVtXfkFBbskcnm8wbmFGn2+qOu022ZGkfOxJgf1lnV3d93ETD7GxbnBQTz8UPmZbSmoOsAfMSlW3zivQ3cj8utMGT5cf0GmSpMf1pRt49t6SFoAxSCkuJ++dDMu+bZrUHlB44b9RJHW5Uh/5A7qL9SOuGcRk4H2kMDKDlIuDiWhOUjhZ0t7b9NaDQWgnig6Lx4Qbdbj44JjEqIf8nukuTiw2OwfUwt6FW5AE9XZEoq1ExXFW1Oz6ANPem6TZJmfeXBg+rXJqCMuiOZ0Fg5fcEdUaDF9kj7un4uizWbuLJ3LgCYRUmGdrSMPUL+OLDK4PnYz+pbM5hjxnSrJoPTfHHmSH0vRUoJmGktBX8KUccSc1tIYt+ppIA92fmcM=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantique
    token:
      secure: LlboIUDhx+4rrXSy1l539Cy+xY2gUK4JHD6u3O0W3XHXF85WpkGWLtBwFe3KNb7Rg6B44l2X0cjQEPMMttKymwsd970XNESwUmVCAOCNRL706eZGV9J5sy5MDhSX22QwTZankl3tAbBS3RPRfcGmUT98jcQiL9BYRLivl3iW5Dwvd3rrghic4X9cYcvZSs6vzbzJxUvhWOCuouCoM/vEX9FezOWe2/6oqVuxK+yasSwW6F/C19o9Me6gzjYGBTEMz+m3s95OqQV1mE9mHuf3HRpE1aUqVBrZsKh+yeSIREwda67yK+lCjNSFU0ZfZBAI86cib7/cXIkq12xdbqGLPGTMalkcc62vDnMyaVQylL7xGcGK7peDpNX/sonYXGxTiKZ1P9GsxB17aIZldxIF3xd9mGpHdW1/gbtpHQ5+XrPlTspiiZHDNZjGVVUCfJ326MA7Q1IUIGAkZXIRTF/QDs9/fBo3PFKhv8Eb59BWcuihiUxTt2Kk9ThpeyLhm4wyahyyc7mL5GhmBO8EtTeiP/jHR46Zt68WLdRN9+TAhWvW/LVyu0dAFYDoD3UguD0ybgCSfjgWueKgHbfsQ6FUCfE9fofQgKBmSVt5OI67CpR7yJaSxVbV+/Eb6uhZfIXcEgAq8O1xURA4Xpg9R4NJfwBqmHVcC93QeBOCJUVsmyk=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull julienbayle/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t julienbayle/jplatformbuild
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: YtdRH8A7pl7feuoCqBL3GaOrz8ln9M3dnVyAjxVKeRbvLjJ6kJuR8MWYnf8Ioq8etkf9toOQ6sq0XB2ps0c3hwI0SRyDbXPuSUDfeZu4Q3/XU35mwKeyFYF+nAcPO7wKLpIKZJDtT1/GwMjDVTOTP8viLWKqdlCk2enCf4HRm6Ui2NeXx8OC/lqbiCDiwAa5hoBOwaPT4DH1lZ6FhvE/4IutEtI60o2NdssqUF9oL5Ua96IB9NJFuOTshuAJbI19JrneEf9Gx2EUm4Yj3n86UWedntrJZDsnkmVANSwK1lQUwg8z9rLLOV91zdNK4NZJtNkHBLEmemvQOBjLeiM8o1OZddtSR53AF3C1wG66zLsxpB7w8IyESZZkhyGQw1zMKNRJls9Aus/8851oS9NkCJXH0oUlJEOqsBZLxixQwxQx4Gnf/VxyQAkuQKoS2tBJVLhXdujlChiBXPCyCCTUP4A6vtrs9I7wyGH83zMzhlMF7hdWPS8xmMXxWZrDHpEtvDXHXAzz2QvDUeZYCNZVhWYynZcHGkxEULJpZJl1S/i6CMUlcPUwxLk8jvJKkWn6dwv/gEiW+ocIVtlvuEouFqMugvZyzQmu+C07H13/vSn9idI9kv5/+Jbbphw1MLDn+C25lWWLHTHUUTysFwOSQPP51hhp62nDHO8VbzTRCmg=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
